---
-   hosts: all
    become: yes
    become_user: root
    user: vagrant

    # environment:
    #   https_proxy: "{{ lookup('env', 'https_proxy') }}"

    tasks:
      - name: remove old docker package
        apt: pkg={{ item }}
        with_items: 
          - docker
          - docker-engine
          - docker.io
        state: absent
        ignore_errors: True

      - name: get os name release
        shell: uname -r
        register: osname

      - name: install pacakages are dependent on docker
        apt: pkg={{ item }}
        with_items:
          - linux-image-extra-{{ osname.stdout }}
          - linux-image-extra-virtual
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

      - name: check docker gpg key.
        shell: apt-key fingerprint 0EBFCD88 | grep 0EBFCD88
        register: docker_gpg
        ignore_errors: True
        changed_when: False

      - name: Add Docker’s official GPG key
        shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        when: docker_gpg | failed

      - name: define lsb_release -cs
        shell: lsb_release -cs
        ignore_errors: True
        register: lsb_release

      - name: add source repository into sources list.
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
          state: present

      - name: Install docker-ce
        apt: name=docker-ce state=present update_cache=yes

      # set group for running docker without sudo
      - name: add docker group
        group: name=docker

      - name: add vagrant docker group
        user:
          name: vagrant
          groups: docker
  
      - name: allow to access the remote API
        ufw:
          rule: allow
          port: 2375
          proto: tcp

      - ufw:
          state: reloaded  

      - service:
          name: docker
          state: stopped

      - copy:
          src: /vagrant_config/docker-daemon-config.json
          dest: /etc/docker/daemon.json
          owner: vagrant
          group: docker

      - service:
          name: docker
          state: started
