# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://{proxy_ip}:{proxy_port}"
    config.proxy.https    = "http://{proxy_ip}:{proxy_port}"
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end

  config.vm.network "private_network", ip: "192.168.50.4"
  # OS => ubuntu_vagrant
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # for remote docker api
  config.vm.network "forwarded_port", guest: 2375, host: 2375
  
  # OS <=> ubuntu_vagrant
  config.vm.synced_folder "./config", "/vagrant_config"
  
  config.vm.synced_folder "../sync_data/data", "/vagrant_data"
  config.vm.synced_folder "../sync_data/htdocs", "/vagrant-htdocs"
  config.vm.synced_folder "../sync_data/apachelog", "/vagrant-apachelog"
  config.vm.synced_folder "../sync_data/varlog", "/vagrant-varlog"
  
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2056"
  end

  config.vm.define vm_name = "ubuntu-vagrant" do |config|
    config.vm.hostname = vm_name
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "vvvv"
    ansible.limit = "all"
  end
end
